[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

[rpc_endpoints]
arbitrum = "${ARBITRUM_RPC_URL}"

[etherscan]
arbitrum = { key = "${ARBISCAN_API_KEY}" }